### ISSUE TITLE
Missing Inspector Reference

### ISSUE THREAD

**Issue by TheoWong-pixel** [Unity-Technologies/com.unity.toonshader#179]
https://github.com/Unity-Technologies/com.unity.toonshader/blob/276406178f29a3e9baeb3b2ccec1e765e3ddf1d8/com.unity.toonshader/Documentation~/AngelRing.md?plain=1#L13

I would recommend an image of the UI for this section of the toon shader.

**Comment by H3idi-X** [comment]
Added An Inspector image.
