### ISSUE TITLE
Re-wording

### ISSUE THREAD

**Issue by TheoWong-pixel** [Unity-Technologies/com.unity.toonshader#181]
https://github.com/Unity-Technologies/com.unity.toonshader/blob/276406178f29a3e9baeb3b2ccec1e765e3ddf1d8/com.unity.toonshader/Documentation~/AngelRing.md?plain=1#L40

Correction:
Texture alpha channel is a clipping mask. If disabled, the alpha is not affected at all. The color of the **Angel Ring** can be specified directly instead of using the additive method.

I'm not sure if you mean 'Affected' or 'applied' here. Please use the right one to your discretion

**Comment by H3idi-X** [comment]
Fixed.
