### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by TheoWong-pixel** [Unity-Technologies/com.unity.toonshader#182]
https://github.com/Unity-Technologies/com.unity.toonshader/blob/276406178f29a3e9baeb3b2ccec1e765e3ddf1d8/com.unity.toonshader/Documentation~/AngelRing.md?plain=1#L42

Correction
Example Texture | Applied the texture with **Alpha Channel as Clipping Mask**

**Comment by H3idi-X** [comment]
All the typos are fixed. thanks to Vale and Thank you!.
