### ISSUE TITLE
More information please

### ISSUE THREAD

**Issue by TheoWong-pixel** [Unity-Technologies/com.unity.toonshader#184]
https://github.com/Unity-Technologies/com.unity.toonshader/blob/276406178f29a3e9baeb3b2ccec1e765e3ddf1d8/com.unity.toonshader/Documentation~/Basic.md?plain=1#L31

**Comment by TheoWong-pixel** [comment]
Please explain what does Base Color : Texture(sRGB) × Color(RGB) mean, this is only accessible high level users

**Comment by H3idi-X** [comment]
Base Color : Texture(sRGB) × Color(RGB). The default color is White. The base color represents the color of the unshaded area of object or character.
