### ISSUE TITLE
Missing Ui reference

### ISSUE THREAD

**Issue by TheoWong-pixel** [Unity-Technologies/com.unity.toonshader#187]
https://github.com/Unity-Technologies/com.unity.toonshader/blob/276406178f29a3e9baeb3b2ccec1e765e3ddf1d8/com.unity.toonshader/Documentation~/Emission.md?plain=1#L1

Missing UI Reference, please provide an image of the UI in this section

**Comment by H3idi-X** [comment]
Added An Inspector image.
