### ISSUE TITLE
Elaborate on section

### ISSUE THREAD

**Issue by TheoWong-pixel** [Unity-Technologies/com.unity.toonshader#189]
https://github.com/Unity-Technologies/com.unity.toonshader/blob/276406178f29a3e9baeb3b2ccec1e765e3ddf1d8/com.unity.toonshader/Documentation~/Emission.md?plain=1#L85

Please elaborate on this section. This explanation is not very helpful. Share some examples may be helpful

**Comment by H3idi-X** [comment]
Emissive color shifts consistent with view angle. The further out from the front of the camera, the more it changes to [Shifting Target Color](https://docs.unity3d.com/Packages/com.unity.toonshader@0.9/manual/Emission.html#shifting-target-color).
