### ISSUE TITLE
Missing UI reference

### ISSUE THREAD

**Issue by TheoWong-pixel** [Unity-Technologies/com.unity.toonshader#190]
https://github.com/Unity-Technologies/com.unity.toonshader/blob/276406178f29a3e9baeb3b2ccec1e765e3ddf1d8/com.unity.toonshader/Documentation~/Highlight.md?plain=1#L1

Please insert reference image of the UI

**Comment by H3idi-X** [comment]
Added UI Screen Shots to all the pages.
