### ISSUE TITLE
re-word

### ISSUE THREAD

**Issue by TheoWong-pixel** [Unity-Technologies/com.unity.toonshader#194]
https://github.com/Unity-Technologies/com.unity.toonshader/blob/276406178f29a3e9baeb3b2ccec1e765e3ddf1d8/com.unity.toonshader/Documentation~/Highlight.md?plain=1#L36

Re-word:
Specular color blending mode allows the user to control the hardness of the colour applied to the highlight. Users have two options: Multiply or Add. Note that **Color Blending Mode** is disabled when **Specular Mode** is set to **Soft**.

**Comment by H3idi-X** [comment]
Fixed. Thanks.
