### ISSUE TITLE
Merge page?

### ISSUE THREAD

**Issue by TheoWong-pixel** [Unity-Technologies/com.unity.toonshader#195]
https://github.com/Unity-Technologies/com.unity.toonshader/blob/276406178f29a3e9baeb3b2ccec1e765e3ddf1d8/com.unity.toonshader/Documentation~/Known-issue.md?plain=1#L1

I think this could be part of the Basic page. This is very little information on a page to have on its own. But you might have to check with Docs standards if its okay to merge this information to another page.

**Comment by H3idi-X** [comment]
I checked URP and HDRP pages.
We see independent known issue pages for both of above. 
UTS team follows their style and leaves UTS know issue page independent from other pages. 

https://docs.unity3d.com/Packages/com.unity.render-pipelines.high-definition@16.0/manual/Known-Issues.html
https://docs.unity3d.com/Packages/com.unity.render-pipelines.universal@16.0/manual/known-issues.html
