### ISSUE TITLE
Remove 's'

### ISSUE THREAD

**Issue by Vic-Cooper** [Unity-Technologies/com.unity.toonshader#196]
https://github.com/Unity-Technologies/com.unity.toonshader/blob/276406178f29a3e9baeb3b2ccec1e765e3ddf1d8/com.unity.toonshader/Documentation~/whats-new-0.7.x.md?plain=1#L11

"documentation" should be singular, not plural. Please correct this headline to "New documentation".

**Comment by H3idi-X** [comment]
s is removed.
