### ISSUE TITLE
Unity Docs review Emission.md

### ISSUE THREAD

**Issue by Vic-Cooper** [Unity-Technologies/com.unity.toonshader#209]
https://github.com/Unity-Technologies/com.unity.toonshader/blob/276406178f29a3e9baeb3b2ccec1e765e3ddf1d8/com.unity.toonshader/Documentation~/Emission.md?plain=1#L1

Please provide a menu path or instructions for the user to enable Emission. 

To conform with the Unity docs style guide, the properties on this page should be in a table under the heading "Properties", instead of sub-headings. You can include images in a table.

**Comment by H3idi-X** [comment]
This is  a block in the inspector window. I added an image of the block.
