### ISSUE TITLE
FeatureModel_en.md

### ISSUE THREAD

**Issue by Vic-Cooper** [Unity-Technologies/com.unity.toonshader#210]
https://github.com/Unity-Technologies/com.unity.toonshader/blob/276406178f29a3e9baeb3b2ccec1e765e3ddf1d8/com.unity.toonshader/Documentation~/FeatureModel_en.md?plain=1#L1

Add a title to this page and introduce what this table is describing.

**Comment by H3idi-X** [comment]
Added a tittle in the document.
