### ISSUE TITLE
Toon-shaded plane cannot be selected

### ISSUE THREAD

**Issue by CawawaC** [Unity-Technologies/com.unity.toonshader#238]
**Describe the bug**
A plane with a toon material cannot be selected from the front in the scene view. 
It is possible to select it from the back (its invisible side).

**To Reproduce**
1. Create a toon material
2. Create a plane in the scene
3. Apply the material to the plane
4. Try and click on the plane's front in the Scene View.

**Expected behavior**
A plane should remain selectable normally, from the front.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Unity version 2022.1.10f1

**EDIT**: Removing the Outline pass from the shader code fixes the issue.

**Comment by H3idi-X** [comment]
Sorry for late reply and thanks for providing the solution.
We believe it won't be avoidable as long as outline pass is working.

**Comment by H3idi-X** [comment]
It is by desgn in the Scene View. Back face polygons can not be selected.
