### ISSUE TITLE
Bloom Issue

### ISSUE THREAD

**Issue by MJAnsell** [Unity-Technologies/com.unity.toonshader#248]
**Describe the bug**
When importing a custom mesh (fbx from Blender 3.3.1), some of them (seemingly flat faces) are causing the built in bloom to behave strangely/be over exposed filling the screen. The faces of the mesh causing it are completely black. This only occurs when using the toon shader/material and only with certain custom meshes (others seem to work fine). All export settings are the same for meshes working correctly, all normals are facing the correct way etc. When rotating the objects that have the issue, the bloom behaves as expected (even by the slightest rotation of 0.01) - see attached.

**To Reproduce**
Unsure on reproduction - some meshes work fine and others don't.

**Expected behavior**
Bloom should not be so strong and flood faces black.

**Screenshots**
https://user-images.githubusercontent.com/50808370/194706349-ac4e6c97-02d3-4358-963a-84d0ba6230fd.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Unity 2021.3.11f1 (URP)

**Comment by H3idi-X** [comment]
Hi, Thanks for reporting.
Will you please submit some reproducible fbx files you created?

**Comment by MJAnsell** [comment]
> Hi, Thanks for reporting. Will you please submit some reproducible fbx files you created?

Here are the models used in the video along with another that had the same issue - the download link will last 1 week but let me know if you need me to renew it, thanks!

https://we.tl/t-kBNNNr5Cc0

**Comment by H3idi-X** [comment]
Hi, as far as we tested using Unity Toon Shader 0.8.2-preview, we weren't able to reproduce the issue.
If you want to continue to ask us issue to check this issue. you need to submit the project, we can easily reproduce the issue. not just fbx.
thanks

![image](https://user-images.githubusercontent.com/4477357/201498107-d9fb52ab-2454-45a7-aaa7-c68f31ae47ff.png)

**Comment by H3idi-X** [comment]
Here is another result.
![image](https://user-images.githubusercontent.com/4477357/201551206-c34d5edc-ce20-4d68-af55-a1a637f037e6.png)

**Comment by H3idi-X** [comment]
We'll close this issue. But, you can reopen this when you put minimam reproducable projects.
