### ISSUE TITLE
How could we upgrade SD Kohakuchanz material properly ?

### ISSUE THREAD

**Issue by Thaina** [Unity-Technologies/com.unity.toonshader#251]
**Describe the bug**

Since there is this package SDKohakuchanz from 2016 https://unity-chan.com/download/releaseNote.php?id=SDKohakuchanz that using outdated built-in material, unlike other package (SD Tokochanz https://unity-chan.com/download/releaseNote.php?id=SD_Toko and other similar package released in the same time at 2019). When we switch to this repo's shader it give me weird lighting effect like below screenshot

I can't find newer version of this package and cannot find a way to properly upgrade these material. It seem the format of texture and material (of 2016) was also not the same as newer version (2019)

So is it possible to create new package for these model or have a script to upgrade the old material into newer version? Or is there an updated package I could downloaded from?

**To Reproduce**
1. Go to https://unity-chan.com/download/releaseNote.php?id=SDKohakuchanz 
2. Import unitypackage
3. Switch magenta material's shader into toon

**Expected behavior**
It should set default material as proper as possible

**Screenshots**

![image](https://user-images.githubusercontent.com/1042507/205500981-6df395d2-ea71-4288-af6f-7b3852f9121a.png)

![image](https://user-images.githubusercontent.com/1042507/205553563-583748e2-650d-4ffa-9949-5a8ee2659af3.png) ![image](https://user-images.githubusercontent.com/1042507/205553584-adc17e4a-cd9f-4108-831d-499a51c80f73.png)

**Additional context**

Alternatively please make a package for all SD character with newer version of shader in the same config pattern

**Comment by H3idi-X** [comment]
We checked them.
They don't use UTS.
