### ISSUE TITLE
Dots Instancing is not enabled. How to get to work in subscene?

### ISSUE THREAD

**Issue by marvalgames** [Unity-Technologies/com.unity.toonshader#268]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Hum9183** [comment]
@H3idi-X 
Hi!
After a light modification, it seems to be working well,
may I create a PR? (URP Only)

**Comment by H3idi-X** [comment]
Oh, thanks! Actually, we didn't have  time.
Will you please submit that PR? Of cource URP only is OK.

**Comment by H3idi-X** [comment]
Thanks to the big contribution, @Hum9183, we created a new brach and merged your PR to [it](https://github.com/Unity-Technologies/com.unity.toonshader/tree/dev/dots-instancing-urp).
We have succeeded to pass our internal tests for the branch.
We will evaluate the dot instancing feature.

**Comment by H3idi-X** [comment]
Hi, we created **dev/dots-instancing-urp-sample** branch and started to evaluate the PR. The project in the branch is **Toonshader_ProjectURP_ECS**.  We converted AngelRing scene ECS comaptible and it look work fine. We will do the same to some other scenes.

**Comment by H3idi-X** [comment]
HI, @Hum9183. we enabled forward+ in **Toonshader_ProjectURP_ECS** and loaded the converted scene like **AngelRing** on **Mac Editor** 2023.3.23f1, we  see the errors attached. We are on investigation into them. We don't see any errors in **RenderMeshUtilityExample** in **ECS_ProjectURP** project in the branch.
<img width="1690" alt="Screenshot 2024-04-15 at 6 37 55" src="https://github.com/Unity-Technologies/com.unity.toonshader/assets/4477357/bb46acf4-d7a4-417c-b8bf-27d530a652b1">
<img width="1690" alt="Screenshot 2024-04-15 at 6 53 07" src="https://github.com/Unity-Technologies/com.unity.toonshader/assets/4477357/d85af71c-3659-4935-81ce-ff49e55af05c">
<img width="1689" alt="Screenshot 2024-04-15 at 6 54 46" src="https://github.com/Unity-Technologies/com.unity.toonshader/assets/4477357/5d03b8a8-b8ce-40fd-892c-926d92516381">

**Comment by H3idi-X** [comment]
This was when using 2022.3.0f1. When using 2022.3.23f1 we see the same error. However, it doesn't occur in lit shader. So, we might have to fix this.

> We don't see any errors in RenderMeshUtilityExample in ECS_ProjectURP project in the branch.

**Comment by Hum9183** [comment]
Hi, @H3idi-X !
https://forum.unity.com/threads/undeclared-idendifier-_foveated_rendering_non_uniform_raster-with-urp-16-0-5-on-metal.1560631/
It seems to be a bug according to this forum. You may be able to find a solution here.

By the way, I don't have a Mac PC, so it is difficult for me to check the metal :(

**Comment by H3idi-X** [comment]
Thanks for the pointer.
I guess so too. I will check that from which version including the file is necessary.

![image](https://github.com/Unity-Technologies/com.unity.toonshader/assets/4477357/81fc052f-6d42-419c-9335-15837d90dfa9)

**Comment by H3idi-X** [comment]
looks working with [this fix](https://github.com/Unity-Technologies/com.unity.toonshader/blob/abbe78f9107267e1ae371764501350a2506fadac/com.unity.toonshader/Runtime/Integrated/Shaders/UnityToon.shader#L1230-L1246). After making some image tests for entities graphics, we will proceed more tests.
