### ISSUE TITLE
Bug in UTS3Converter.cs

### ISSUE THREAD

**Issue by Kurados** [Unity-Technologies/com.unity.toonshader#279]
Bug in UTS3Converter.cs

I just import Toon Shader from [com.unity.toonshader](https://github.com/Unity-Technologies/com.unity.toonshader). 
Then I got an error, it said "Library\PackageCache\com.unity.toonshader@0.8.5-preview\Editor\Converter\UTS3Converter.cs(159,39): error CS0122: 'BasePopupField<string, string>.choices' is inaccessible due to its protection level"

![Screenshot (2237)](https://user-images.githubusercontent.com/89411136/222707331-67c57686-1ec9-4288-9317-21dcf8b64b61.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Unity Version: 2020.3.20f1

**Comment by H3idi-X** [comment]
Hello, we apologize for the inconvenience, but we are unable to support some versions of Unity. 2020.3.20f1 is not supported, and the minimum version is 2020.3.25f1. Please check the manual for the supported Unity versions. The next release of this version will be 2020.3.45f1 or later. https://docs.unity3d.com/Packages/com.unity.toonshader@0.8/manual/System-Requirements.html

**Comment by Kurados** [comment]
Thank you for your immediate response. I update my unity version to
2020.3.45, and it works. Thank you. Toon shader is wonderful. Keep up the
good work!

**Comment by H3idi-X** [comment]
We are relieved to hear that the problem has been resolved. Thank you again for your kind words.
