### ISSUE TITLE
Shader error in 'Toon': undeclared identifier 'sampler_LinearClampCompare'

### ISSUE THREAD

**Issue by imannms000** [Unity-Technologies/com.unity.toonshader#288]
* Unity version: 2022.2.9f1
* URP version: 14.0.6
* UTS version: 0.9.0-preview
* Template: URP 3D

This is a new empty project.

**Describe the bug**
I followed this doc on how to install UTS: https://docs.unity3d.com/Packages/com.unity.toonshader@0.9/manual/installation.html

And then I got an error:

```
Shader error in 'Toon': undeclared identifier 'sampler_LinearClampCompare' at URP/Library/PackageCache/com.unity.toonshader@0.9.0-preview/Runtime/UniversalRP/Shaders/UniversalToonBody.hlsl(238) (on d3d11)

Compiling Subshader: 1, Pass: ForwardLit, Fragment program with _EMISSIVE_SIMPLE _IS_ANGELRING_OFF _IS_CLIPPING_OFF _IS_TRANSCLIPPING_OFF
Platform defines: SHADER_API_DESKTOP UNITY_ENABLE_DETAIL_NORMALMAP UNITY_ENABLE_REFLECTION_BUFFERS UNITY_LIGHTMAP_FULL_HDR UNITY_LIGHT_PROBE_PROXY_VOLUME UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BLENDING UNITY_SPECCUBE_BOX_PROJECTION UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS
Disabled keywords: DIRLIGHTMAP_COMBINED FOG_EXP FOG_EXP2 FOG_LINEAR LIGHTMAP_ON SHADER_API_GLES30 UNITY_ASTC_NORMALMAP_ENCODING UNITY_COLORSPACE_GAMMA UNITY_FRAMEBUFFER_FETCH_AVAILABLE UNITY_HALF_PRECISION_FRAGMENT_SHADER_REGISTERS UNITY_HARDWARE_TIER1 UNITY_HARDWARE_TIER2 UNITY_HARDWARE_TIER3 UNITY_LIGHTMAP_DLDR_ENCODING UNITY_LIGHTMAP_RGBM_ENCODING UNITY_METAL_SHADOWS_USE_POINT_FILTERING UNITY_NO_DXT5nm UNITY_NO_FULL_STANDARD_SHADER UNITY_NO_SCREENSPACE_SHADOWS UNITY_PBS_USE_BRDF2 UNITY_PBS_USE_BRDF3 UNITY_PRETRANSFORM_TO_DISPLAY_ORIENTATION UNITY_UNIFIED_SHADER_PRECISION_MODEL UNITY_VIRTUAL_TEXTURING UTS_USE_RAYTRACING_SHADOW _ADDITIONAL_LIGHTS _ADDITIONAL_LIGHTS_VERTEX _ADDITIONAL_LIGHT_SHADOWS _EMISSIVE_ANIMATION _FORWARD_PLUS _IS_ANGELRING_ON _IS_CLIPPING_MODE _IS_CLIPPING_TRANSMODE _IS_TRANSCLIPPING_ON _MAIN_LIGHT_SHADOWS _MAIN_LIGHT_SHADOWS_CASCADE _MIXED_LIGHTING_SUBTRACTIVE _SHADINGGRADEMAP _SHADOWS_SOFT
```

Other people also get the same error with Unity 2022.2.11f1 https://forum.unity.com/threads/massive-breaking-changes-in-urp-14-0-6-in-unity-2022-2-11.1414086/

**To Reproduce**
1. Open new project with URP 3D template using Unity 2022.2.9f1
2. Add package from git url: `com.unity.toonshader`
3. Wait for the package manager to finish installing UTS
4. Create a new material and change the shader to the `Universal Render Pipeline/Toon` shader. But due to shader compilation error you can't find it there, instead you can find it in `Failed to compile/Toon`. Change the shader to `Failed to compile/Toon`.
5. See error

**Expected behavior**
UTS installed successfully without error.

**Comment by H3idi-X** [comment]
Thank you for using Unity Toon Shader.
The 0.9.x-preview is compatible with 2022.2.11f1 or later, and we apologize for the inconvenience, as there is no way to apply this requirements in the Package Manager.
Will you please use 2022.2.11f1 or later?
You can find the information about Unity versions in the manual [here](https://docs.unity3d.com/Packages/com.unity.toonshader@0.9/manual/System-Requirements.html).
