### ISSUE TITLE
Toon is not in the URP shader option.

### ISSUE THREAD

**Issue by tmanallen** [Unity-Technologies/com.unity.toonshader#290]
**Describe the bug**
After installing the package from git, or even from disk, toon doesn't show up in the URP dropdown list.

**To Reproduce**
1. Go to package manager and install the package with the latest preview.
2. Click on  add new material and then add a shader from the URP menu
3. Scroll down the list and you won't see it there.

**Expected behavior**
You are supposed to see toon in the options list.

**Screenshots**
Unable to get a scr

**Desktop (please complete the following information):**
 - OS: WIndows 10
 - Browser Chrome

Version of Unity I am using is 2022.2.8f1

**Additional context**

**Comment by H3idi-X** [comment]
Thank you for using Unity Toon Shader.
The latest preview means 0.9.0-preview?
The 0.9.x-preview is compatible with Unity versions described in [System-Requirements](https://docs.unity3d.com/Packages/com.unity.toonshader@0.9/manual/System-Requirements.html). We apologize for the inconvenience. Currently, there is no way to handle these requirements in the Package Manager.

**Comment by tmanallen** [comment]
Ok, I am using the latest preview.
My unity version is 2022.2.8f1, shouldn't that work?

**Comment by tmanallen** [comment]
Ok, I see now, I didn't see 2.11, I am using 2.12 now.

**Comment by H3idi-X** [comment]
My apologies. I misunderstood your question, Unity Toon Shader is compatible with three Unity render pipelines: built-in, URP, and HDRP. The shader does not appear in the URP menu, it is in the Shaders menu directory. Documentation will be modified.
![image](https://user-images.githubusercontent.com/4477357/228095470-33c3fc8d-1a21-4bcb-b7c3-55fb2b19b0bb.png)

**Comment by tmanallen** [comment]
Ok, thank you. I thought I had missed something.
