### ISSUE TITLE
Shader Compilation Error (undeclared identifier 'builtinData')

### ISSUE THREAD

**Issue by skedgyedgy** [Unity-Technologies/com.unity.toonshader#310]
**Describe the bug**
Shader compile error on Unity 2022.3.1f1 with HDRP 14.0.8.

**To Reproduce**
Install Unity Toon Shader.
No shaders compiled.

**Expected behavior**
Shaders compile.

**Screenshots**
![image](https://github.com/Unity-Technologies/com.unity.toonshader/assets/96351114/3f17028c-4ab4-4f82-ac03-bf1986738109)

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by H3idi-X** [comment]
Will you please give us more specific information? 
As far as we tested HDRP UTS project with Unity 2022.3.1f1, we don't see those kinds of errrors.
![image](https://github.com/Unity-Technologies/com.unity.toonshader/assets/4477357/91d5d3c1-e890-4deb-abb9-139c9b6ffa2f)

**Comment by H3idi-X** [comment]
Hi, @skedgyedgy . Are you still in trouble when using 2022.3.1f1 and HDRP?

**Comment by H3idi-X** [comment]
Hi, can we ask how is the result you see now?.
If there is no response, we will close this issue in a few days.
