### ISSUE TITLE
Outline with mesh normals and with HDRP realistic sky

### ISSUE THREAD

**Issue by immorrtalz** [Unity-Technologies/com.unity.toonshader#321]
**Describe the bug**
1. Idk if it's supposed to be like this, but on sharp normals, the outline is a little weird... Actually, on the default 3rd person character it's okay, but on custom model... Just see screenshots
2. Color of outline is half-transparent when HDRP realistic sky with clouds is behind

**To Reproduce**
1. Create `Toon` shaded material (I'm on HDRP, with `Toon (Tessellation)` It's much more weird)
2. Click on `Outline`
3. Select any outline mode (yes, ANY of two)

**Expected behavior**
The outline should be uniform across the entire surface of the mesh.

**Screenshots**
![1](https://github.com/Unity-Technologies/com.unity.toonshader/assets/61843974/aa662b54-8eb9-426a-b020-158c0b761aac)
![2](https://github.com/Unity-Technologies/com.unity.toonshader/assets/61843974/b08d1e42-ad62-465b-a823-f9aa719827fa)
![3](https://github.com/Unity-Technologies/com.unity.toonshader/assets/61843974/1479ae10-08b6-4441-9636-266cba1a3cff)
![4](https://github.com/Unity-Technologies/com.unity.toonshader/assets/61843974/47c20530-0b98-43a9-89d6-374136d76699)
![5](https://github.com/Unity-Technologies/com.unity.toonshader/assets/61843974/f8380776-1013-46aa-a138-672e08d3ba68)

**Desktop:**
 - OS: Windows 11
 - Unity 2022.3.3f1 HDRP LTS

**Additional context**
I'll use two shaders: this one and another - for the outline; however, fewer materials would be better...

**Comment by H3idi-X** [comment]
Hi, will you upload projects which we can check the issues?.

**Comment by H3idi-X** [comment]
Hi, we succeeded to reproduce this issue. We are fixing this  
![image](https://github.com/Unity-Technologies/com.unity.toonshader/assets/4477357/6ce0fbb6-f0b9-4aa3-b9fc-17ab1b98eb65)

**Comment by immorrtalz** [comment]
Sorry for such a delayed reply, was busy with some projects and a gamejam...
Here is a link to a model with sharp edges: https://drive.google.com/file/d/1LF5Zh1Vv6jjHnlTHs1FStLbMxZIMst0u/view?usp=sharing
Or is it intended that the outline is not solid and has gaps? Of course, this shader is mainly used on characters that usually have a smooth surface and on the ThirdPersonController's test character it works as it should, but still...
It's weird...
![header-background](https://github.com/Unity-Technologies/com.unity.toonshader/assets/61843974/29abf9d8-77a1-49cb-91e3-190a91ba31e6)

**Comment by H3idi-X** [comment]
Thanks for the additional information.

The outline of the UTS is created by expanding the polygon in the direction of the normals. Therefore, if the edges are not smooth, this is unavoidable: if there are two or more normals on a single vertex, the polygon will be expanded in each direction. Then the normals pointing in separate directions will be extended, no polygon will be generated between them, and no outline will be displayed. This is a specification.

To work around this, the edges must be smoothed.
![image](https://github.com/Unity-Technologies/com.unity.toonshader/assets/4477357/d017e8dc-7303-4c22-bc2b-9235a6034a9e)
