### ISSUE TITLE
Shadow Casting/Receiving not working

### ISSUE THREAD

**Issue by vidocco** [Unity-Technologies/com.unity.toonshader#322]
**Describe the bug**

Toon shader: v 0.9.4
Unity: 2023.1.0b

I'm using Toon shaders in all objects on my scene, all of them are set as static, have shadow casting/receiving enabled everywhere (shader, mesh) and are using lightmaps. All lights in the scene are "Mixed" and have "cast shadows" enabled. None of the objects receive shadows as they should.

Shadowmask view correctly displays shadows where I would expect them. Changing materials to "Lit" displays shadows correctly.

**To Reproduce**
1. Create a Scene.
2. Set renderer to "Forward", "Forward+" or "Deferred".
3. Add a light set to mixed and enable "cast shadows"
4. Add a mesh with a toon shader and another one under it with another toon shader. Make sure both shaders have "receive shadows" enabled and both meshes have "cast shadows" enabled. Set them both as static.

**Expected behavior**
Mesh above should be casting a shadow to the mesh under it, mesh underneath should receive the casted shadow.

**Screenshots**
Toon Shader results:
![image](https://github.com/Unity-Technologies/com.unity.toonshader/assets/30317944/4da42e60-8b60-4c8e-bb63-fb8d1623d3d5)

Shadow Mask view:
![image](https://github.com/Unity-Technologies/com.unity.toonshader/assets/30317944/98edecb6-10f6-43e7-b2b7-e3b7d435d2e3)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox

**Comment by vidocco** [comment]
I've tried everything I could think of so far: setting everything to real time, using shadowmask/subtractive/baked indirect, setting up and removing probe volumes, increasing albedo of lighting settings, manually generating lightmap uvs and even went into the code directly.

Since it's pretty lacking in documentation I wasn't able to find where/how it's supposed to add shadows from other objects (it seems like it only accounts for light attenuation from light sources, not for shadows themselves). I did, however, create my own custom version of this shader to be able to tinker with it a bit and I did manage to get some lighting settings to work better.

Still would love some input on whether this is even supported.

**Comment by H3idi-X** [comment]
I am sorry to hear that you are strugglling with receiving shadows on toon shader objects.
Will you please upload the project you use?

**Comment by vidocco** [comment]
Sorry but I can't do that. I did manage to get shadow casting to work (only in real time though) by messing around with the shader/code. Basically: we weren't using shadowAttenuation anywhere for any of the lights (added that), the "receive shadows" toggle was doing nothing (because it was being skipped entirely). I also figured there was no Meta pass in the shader (so I added that too) and there were some weird choices when it came to processing lighting input.

Can't go into much details right now but I'd be happy to share my hacky version of this if you want...

**Comment by H3idi-X** [comment]
As far as we tested, we weren't able to reproduce the issue. We see shadow on UTS/URP shader materials.
![image](https://github.com/Unity-Technologies/com.unity.toonshader/assets/4477357/f77f8958-4af8-483e-8d76-e6cf9a06ef52)

**Comment by H3idi-X** [comment]
The following is the sample installation manual:
https://docs.unity3d.com/Packages/com.unity.toonshader@0.9/manual/sample-instlation.html

The setting to receive shadow is described in the followingl:
https://docs.unity3d.com/Packages/com.unity.toonshader@0.9/manual/ShadingStepAndFeather.html

**Comment by H3idi-X** [comment]
Hi, we will close this issue in a few days. The issue can not be reproduced and without reproducable project, it is hard to answer your questions.
