### ISSUE TITLE
Bad Performance (Quest 2)

### ISSUE THREAD

**Issue by Applepiee** [Unity-Technologies/com.unity.toonshader#323]
Hi,

I wanted to use this shader for my URP project for the Oculus Quest 2, however, when I apply the shader to a single character, the performance is really bad. (30FPS).
Can I get some help to optimize it?

**Comment by H3idi-X** [comment]
Hello, 
Can I ask compared to which URP shaders provided by Unity, you feel slow UTS is slow?

**Comment by H3idi-X** [comment]
Hi, it might be tough to answer questions and make some improvement without specific description. We will close this issue in a few days.
