### ISSUE TITLE
RenderQueue is not changed when Clipping is enabled

### ISSUE THREAD

**Issue by TakeshiMiyakawaCR** [Unity-Technologies/com.unity.toonshader#331]
**Describe the bug**
RenderQueue is not changed when AutoRenderQueue is enabled and Clipping is enabled.

**To Reproduce**
Click on Clipping "On" or "Clip Transparency"

**Expected behavior**
RenderQueue set to 2450.
That is how it behaves in [UTS2](https://github.com/unity3d-jp/UnityChanToonShaderVer2_Project/blob/release/legacy/2.0/Assets/Toon/Shader/Toon_DoubleShadeWithFeather_TransClipping.shader#L160).

**Gif**
![UTS_clipping_render_queue_bug](https://github.com/Unity-Technologies/com.unity.toonshader/assets/93700743/efbf4386-568b-42de-acc7-a30c36db6898)

**Environment**
 - OS: Windows 10
 - Unity Version: 2022.3.7f1
 - Render Pipeline: URP
 - UnityToonShader Version: 0.9.5-preview

**Comment by TakeshiMiyakawaCR** [comment]
@H3idi-X 
I have an idea to fix this problem, may I create a PR?

**Comment by H3idi-X** [comment]
Thank you very much  for reporting!
If it doesn't make too much problems, yes please submitting a PR.
Maybe adding something like the following code into  **SetReqnderQueueAuto()**?             


```
if (clippingMode == UTS_ClippingMode.On || clippingMode == UTS_ClippingMode.TransClippingMode)
{
    material.renderQueue = (int)UnityEngine.Rendering.RenderQueue.AlphaTest;
}

```

**Comment by TakeshiMiyakawaCR** [comment]
@H3idi-X 
Thank you for your reply.

```
if (clippingMode == UTS_ClippingMode.On || clippingMode == UTS_ClippingMode.TransClippingMode)
{
    material.renderQueue = (int)UnityEngine.Rendering.RenderQueue.AlphaTest;
}
```
We will make a PR for the revised proposal, as we believe it is as above.

**Comment by H3idi-X** [comment]
Hi, Your PR is merged to our main branch.
Tnak you very much for the report and the contribution!

**Comment by TakeshiMiyakawaCR** [comment]
@H3idi-X 
Thank you for checking the PR.
Now that this issue has been resolved, may I close it?

**Comment by H3idi-X** [comment]
I close this issue.
Thank you!
