### ISSUE TITLE
[URP] Light layers is not supported

### ISSUE THREAD

**Issue by Hum9183** [Unity-Technologies/com.unity.toonshader#337]
https://github.com/Unity-Technologies/com.unity.toonshader/issues/271#issuecomment-1441280992

https://docs.unity3d.com/Packages/com.unity.render-pipelines.universal@13.1/manual/lighting/light-layers.html

**Comment by misakieku** [comment]
You can add `IsMatchingLightLayer(lightData.lightLayers, builtinData.renderingLayers)` before light model calculation to the shader code by yourself

**Comment by H3idi-X** [comment]
Thanks for the PR. Your PR passed our tests. We are preparing for the new release. It would be in the next month.

**Comment by Hum9183** [comment]
@H3idi-X 
Hi, thank you for releasing 0.9.7-preview.

> I found I had put wrong name into CHANGELOG.md.

We hope you don't mind :)
