### ISSUE TITLE
[HDRP] Toon Shader Rendering Issue with Multiple Materials in Transparency Mode

### ISSUE THREAD

**Issue by AnyCity** [Unity-Technologies/com.unity.toonshader#342]
**Describe the bug**
I have a VRM character with a multi-layered skirt that shares the same Mesh. When I enable Alpha Clipping in HDRP/Lit, the skirt displays correctly. However, when I switch to Toon Shader and set Transparency to On, with Use Base Map Alpha checked, the top layer of the skirt masks all the layers behind it. Since I don't understand the underlying principles, I'm unsure how to adjust settings to resolve this issue.

**To Reproduce**
1. Load VRM character with a multi-layered skirt.
2. Switch to Toon Shader.
3. Set Transparency to On and check Use Base Map Alpha.
4. Observe that the top layer of the skirt masks all layers behind it.

**Expected behavior**

**Screenshots**
![image](https://github.com/Unity-Technologies/com.unity.toonshader/assets/161310180/4d2714a6-c6d3-4ff1-a382-ea85396345d8)
![image](https://github.com/Unity-Technologies/com.unity.toonshader/assets/161310180/13271bd0-362f-45e4-8341-0165d6a19381)

**Desktop (please complete the following information):**
 - OS: Window
 - Unity Version: 2022.3.14f1
 - HDRP Version: 0.9.5-preview

**Comment by H3idi-X** [comment]
Thank you for reaching out about the Unity Toon Shader. The issue you're facing with transparent multi-layered meshes is a common challenge in realtime 3D rendering. To solve this, you'll need to adjust the drawing order or manually sort polygons. This ensures that layers are rendered in the correct sequence, allowing for accurate calculation of transparency relative to other layers.
For more detailed information and examples, you can refer to discussions on this topic in the Unity forums and other websites. Here are some examples from our forum that might help you better understand the issue:

- Problem with material remaining transparent even when at full alpha

https://forum.unity.com/threads/problem-with-material-remaining-transparent-even-when-at-full-alpha.1236706/

- Shaders overlapping transparency

https://forum.unity.com/threads/shaders-overlapping-transparancy.1026079/

**Comment by AnyCity** [comment]
Thank you very much for your response. Can I obtain the correct sorting of HDRP/Lit's RenderQueue and then set the RenderQueue value for the ToonShader? This is because in HDRP/Lit, textures with transparent parts can be displayed correctly as masks.

**Comment by H3idi-X** [comment]
Adapting HDRP's transparent object processing to UTS presents a challenge. UTS, including its HDRP version, follows the same logic as the builtin and URP versions, which are designed for forward rendering exclusively. Simply adjusting the rendering queue may not suffice. As a small team, we cannot support the same approach as HDRP. If you're determined to achieve this, you'll need to delve into transparent object rendering techniques on your own. Many research papers cover this topic in depth.
