### ISSUE TITLE
There is no option to choose between uv0 and uv1 in this shader

### ISSUE THREAD

**Issue by Fpro1383** [Unity-Technologies/com.unity.toonshader#347]
There is no option to choose between uv0 and uv1 in this shader

**Comment by H3idi-X** [comment]
Hi, thank you for using the Unity Toon Shader! We'd like to clarify your question about "my shadow map." In Unity, shadow maps are not rendered using UV coordinates; instead, they are rendered directly to a shadow map texture. You can verify this by using the frame debugger, which allows you to see how the shadow map is generated and used in your scene.

**Comment by H3idi-X** [comment]
We have a different approach and logic from the one proposed, so we currently have no intention of adopting it.
