### ISSUE TITLE
HDRP rendering errors when using adaptive probe volumes (2022.3, 6000.0)

### ISSUE THREAD

**Issue by riina** [Unity-Technologies/com.unity.toonshader#360]
**Describe the bug**
Black flashing occurs when APV (adaptive probe volumes) are enabled.
Observed on 2022.3.33f1 and 6000.0.5f1

**To Reproduce**
1. Open test project [hdrptest_2022.3.33f1.zip](https://github.com/user-attachments/files/15908379/hdrptest_2022.3.33f1.zip)
2. Open OutdoorsScene
3. 2022.3: Ensure that `Project Settings > Quality > HDRP > Lighting > Light Probe Lighting > Light Probe System` is set to `Probe Volumes`
4. Look around in Scene view
5. Observe view occasionally flashing black

**Expected behavior**
The render is stable with no flickering whatsoever.

**Screenshots**
https://github.com/Unity-Technologies/com.unity.toonshader/assets/54872398/a400bebc-ef6e-472a-a81c-f26bf25c429b
When APV is enabled, the screen flashes black. Switching to Light Probe Groups stops this behavior.

https://github.com/Unity-Technologies/com.unity.toonshader/assets/54872398/8a25e067-2740-4964-84b7-f0bdd3408fba
With the below suggested patch, the keywords `PROBE_VOLUMES_L1` and `PROBE_VOLUMES_L2` are recognized within the shader and produce a valid result.

https://github.com/Unity-Technologies/com.unity.toonshader/assets/54872398/ddff6ee0-26a7-44df-b38e-3add0197b770
https://github.com/Unity-Technologies/com.unity.toonshader/assets/54872398/690b37b2-9850-4f87-a5ec-0b7771e4aaab
Properties such as `unity_SHAb` (spherical harmonics values) and `unity_ProbeVolumeParams` (for light probe proxy volume) are uninitialized garbage with APV on. Switching to Light Probe Groups produces the expected result (constant, non-flickering value).

**Desktop (please complete the following information):**
 - OS: Windows 11 23H2 (22631.3737)
 - Graphics API: DirectX 12

**Additional context**
Constants such as `unity_SHC`, `unity_SHBr`, `unity_ProbeVolumeParams` in the `UnityPerDraw` cbuffer appear to be uninitialized garbage when APV is set up. I'm not sure if this is an HDRP/SRP bug, as it looks like these values should go unused for APV. Shaders apparently use `PROBE_VOLUMES_L1`/`PROBE_VOLUMES_L2` variants for APV mode, and handle SSGI accordingly with the preprocessor. `ShadeSH9` and `DecodeLightProbe` are problematic as they only depend on the `UnityPerDraw` coefficients.

At a base level, the shader's outline and forward passes should have variants for APV.
```diff
diff --git a/com.unity.toonshader/Runtime/Integrated/Shaders/UnityToon.shader b/com.unity.toonshader/Runtime/Integrated/Shaders/UnityToon.shader
index 264f151c..3c8a8c99 100644
--- a/com.unity.toonshader/Runtime/Integrated/Shaders/UnityToon.shader
+++ b/com.unity.toonshader/Runtime/Integrated/Shaders/UnityToon.shader
@@ -964,6 +964,8 @@ Shader "Toon" {
             #pragma multi_compile _ LIGHTMAP_ON
             #pragma multi_compile _ DIRLIGHTMAP_COMBINED
             #pragma multi_compile _ DYNAMICLIGHTMAP_ON
+            // Ensure APV path is taken if available
+            #pragma multi_compile_fragment _ PROBE_VOLUMES_L1 PROBE_VOLUMES_L2
             #pragma multi_compile _ SHADOWS_SHADOWMASK
             // Setup DECALS_OFF so the shader stripper can remove variants
             #pragma multi_compile DECALS_OFF DECALS_3RT DECALS_4RT
@@ -1080,6 +1082,10 @@ Shader "Toon" {
             #define SHADOW_LOW
             #define LIGHTLOOP_DISABLE_TILE_AND_CLUSTER
 
+            #pragma multi_compile _ LIGHTMAP_ON
+            #pragma multi_compile _ DYNAMICLIGHTMAP_ON
+            // Ensure APV path is taken if available
+            #pragma multi_compile_fragment _ PROBE_VOLUMES_L1 PROBE_VOLUMES_L2
             #pragma multi_compile _IS_OUTLINE_CLIPPING_NO _IS_OUTLINE_CLIPPING_YES
             #pragma multi_compile _OUTLINE_NML _OUTLINE_POS
             #pragma shader_feature _ _IS_CLIPPING_MATTE
```
From there, the shader would be able to discern whether APV is enabled and act accordingly. For example, as shown in [this commit](https://github.com/Unity-Technologies/com.unity.toonshader/commit/2cc87fdb7b25bf006be401439c900df2fad0ffc5), one could use a function to produce a baked GI value based on the variant. That way, the `Light Probe Intensity` property in UTS will actually have an effect with APV.

In any event, the core of the issue is that it is currently untenable to rely on the spherical harmonics coefficients like `unity_SHC` and also `unity_ProbeVolumeParams` (LPPV) when APV is active.

**Comment by H3idi-X** [comment]
Thank you once again for the detailed report.
Having completed the fix for the issue you previously reported, we have now begun investigating this new issue.

**Comment by H3idi-X** [comment]
Hi, @riina 
We applied your fix to the branch https://github.com/Unity-Technologies/com.unity.toonshader/tree/task/hdrpIssue6000-2
Acctually, we haven't succeeded to reproduce the issue on our site.
But, could you please confirem the fix in the branch works fine for you?

**Comment by riina** [comment]
Hi, thanks for checking. Regarding the fix, adding shader variants is not sufficient on its own, as `ShadeSH9` and `DecodeLightProbe` (which just calls `ShadeSH9`) in HDRPToonHead.hlsl are still used unconditionally, which is what triggers the error.

I can still reproduce this issue with 6000.0.9f1. [Here is a repro project updated for that version.](https://github.com/user-attachments/files/16109746/hdrptest_6000.0.9f1.zip) `OutdoorsScene.unity` in Play Mode causes flashing in the Game view. The scene is saved with TAA enabled on `Main Camera (1)`, which ends up stopping the black flashing but still retains erroneous color flashing on the sphere with the toon shader material. With TAA disabled, the whole Game view flashes black.

For clarity, my graphics card is a GTX 1070 with driver version 556.12 (latest available). My friend with an RTX 3060 on GRD 555.99 can also reproduce the issue.

My actual fix is to replace usages of `ShadeSH9` and `DecodeLightProbe` with something that accounts for APV data, such as `SampleBakedGI` from BuiltinGIUtilities.hlsl in the HDRP package. The full set of changes made for this is in this commit:
https://github.com/Unity-Technologies/com.unity.toonshader/commit/2cc87fdb7b25bf006be401439c900df2fad0ffc5

Note that I copied over the implementation of `SampleBakedGI` into the toon shader package, which for some reason seems to work around an issue where the APV doesn't seem to be sampled, so the contribution is 0 (all black).

**Comment by H3idi-X** [comment]
Thanks for more information!.
I updated the branch. How is it  on your PC?

**Comment by riina** [comment]
The updated branch (task/hdrpIssue6000-2) no longer has any flashing in the repro project, which is excellent.

Also, I tried adding the package to Unity's HDRP sample project. The current main branch has the same erroneous behavior, and the patch branch works without any flashing.

https://github.com/Unity-Technologies/com.unity.toonshader/assets/54872398/9e2b4e64-0534-40ae-bdd6-86715168408d

The shader now works correctly on my end.

**Comment by H3idi-X** [comment]
Thanks for checking.
After conforming it pass some graphics tests, we will merge the branch to development/v1.

**Comment by H3idi-X** [comment]
We merged the branch into development/v1.

**Comment by riina** [comment]
Thank you!
