### ISSUE TITLE
Texture Ramp

### ISSUE THREAD

**Issue by ATHellboy** [Unity-Technologies/com.unity.toonshader#369]
I'm looking for **texture ramp** on Unity Toon Shader. As far as I noticed it is missing currently. But it is achievable by 1st and 2nd Shading Map ?
![TFF_Toon_Ramp_1B](https://github.com/user-attachments/assets/3d5e6b46-684b-46ab-a66d-9836c5cd22af)

Though I'm not sure why we can use simpler texture for controlling brighter and darker portions of the shadow with simple gradient like texture instead of make the entire base texture brighter or darker based on the example in [here](https://github.com/Unity-Technologies/com.unity.toonshader/blob/development/v1/com.unity.toonshader/Documentation~/Basic.md).
Probably because of more controlling on different parts of the texture but I think it would make a development pipeline easiter to use texture ramp instead or at least have another option for texture map.

btw, I want to know if anyone has tried adding it to this shader ?

**Comment by sindharta-tanuwijaya** [comment]
Thank you for your interest in Unity Toon Shader.

The workflow and concept behind Unity Toon Shader are inspired by the shading techniques commonly used in the Japanese animation industry, which typically involves three levels of shading: base, first shading, and second shading. This method may differ from a toon workflow that utilizes a texture ramp for shading.

For detailed instructions on how to control blending in Unity Toon Shader, please refer to the [manual](https://docs.unity3d.com/Packages/com.unity.toonshader@0.9/manual/ShadingStepAndFeather.html).

**Comment by sindharta-tanuwijaya** [comment]
I believe I have addressed this question. Please reopen it if you have any question related to this issue.
